<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;

#[Fillable([
    'organization_id',
    'required_meals',
    'priority',
    'remarks',
])]
class RecipientRequest extends Model
{
    protected function casts(): array
    {
        return [
            'required_meals' => 'integer',
            'priority' => 'string',
        ];
    }

    /**
     * Organization requesting the food.
     */
    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class, 'organization_id', 'id');
    }

    /**
     * Match generated by the matching algorithm.
     */
    public function matchRequest(): HasOne
    {
        return $this->hasOne(MatchRequest::class, 'recipient_request_id');
    }
}
